### ISSUE TITLE
Same MAC, same name - only difference is LE

### ISSUE THREAD

**Issue by Grovkillen** [PolarGoose/BluetoothDevicePairing#1]
Hello and thank you for this tool. Great job.

I've been trying to use it to connect to a portable thermal printer. The problem is that it is broadcasting two interfaces and the only difference between them is that one is LE and one is standard energy mode. Your app is connecting to the LE one which isn't the one I need to use.

As you see in this image below only the LE one (MTP-2) is paired and connected:
![image](https://user-images.githubusercontent.com/26706274/101333135-8d215380-3876-11eb-88ef-161c6f17adb0.png)

**Comment by PolarGoose** [comment]
@Grovkillen,
I didn't know such situation can happen.
Thank you for pointing it out.

I can add code to connect to both devices in case there are 2 LE/non-LE device with the same mac.
Will it fix for your problem? Or you want to connect only to one of them?

**Comment by Grovkillen** [comment]
No both are ok i think. Thanks!

**Comment by PolarGoose** [comment]
@Grovkillen,

Could you please check the latest release? Could you check that pairing/unpairing by name/mac of your device works?

**Comment by Grovkillen** [comment]
Ah great! I will test it first thing tomorrow.

**Comment by PolarGoose** [comment]
@Grovkillen ,

Could you also check to which device your PC connects if you use Windows "Bluetooth & other devices" dialog?

**Comment by Grovkillen** [comment]
Okay, my findings:

- If the BLE is already connected the app will exit after it says "no need for..." It will not continue to the next interface.
- If no BLE or BT is paired it will pair both but only connect to the BLE (I don't know if this is because it's first in the list or if it's due to the interface mode)
- If they both are paired it will connect to the BLE but not the BT (same thing here, I don't know if it's because it's first in the list or not).
- The Windows discover mode will never detect the BT interface once the BLE is connected. So perhaps that's something that is causing problems here?

Would it be possible to have the app first connect to the BT and then BLE?

**Comment by Grovkillen** [comment]
Another thought, the BLE is not password secured. The BT uses the standard "0000".

**Comment by PolarGoose** [comment]
Thank you for the feedback. Looks like my idea with connecting to both devices doesn't work.
I will remove my changes and just add a flag to specify LE nonLE device type. Then you will be able to choose what you want.

**Comment by Grovkillen** [comment]
Yep, sounds like a good idea.

**Comment by PolarGoose** [comment]
I have reverted my previous changes and added "--type" flag to specify Bluetooth/BluetoothLE device. 
Please try the latest release

**Comment by Grovkillen** [comment]
Yep now it's working better. Is it possible to have your tool add the password as well? I now have to manually type in the 0000 code after pairing for it to start printing.

**Comment by PolarGoose** [comment]
> Yep now it's working better. Is it possible to have your tool add the password as well?

It can be tricky. The short answer is that this feature is not available for non UWP applications which use [Windows.Devices.Enumeration API](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.Enumeration?redirectedfrom=MSDN&view=winrt-19041). But recently .Net 5 has been released and Microsoft changed the mechanism of how non UWP application works with this API. Therefore, maybe now it is possible to do that.
But I need time to try it, and I can't promise you that I will be able to do that.

I will create a separate ticket for that.

**Comment by Grovkillen** [comment]
Perfect. Take your time :)
