### ISSUE TITLE
Feature Request: Query if a device is already connected?

### ISSUE THREAD

**Issue by shunf4** [PolarGoose/BluetoothDevicePairing#10]
My [ToothTrayCli](https://github.com/shunf4/ToothTrayCli) has this feature:

```
D:\work\ToothTray\x64\Release>.\ToothTray.exe is-connected "SOUNDPEATS RunFree"
1
```

**Comment by PolarGoose** [comment]
@shunf4,
Thank you for reaching out.
I haven't added clauses like `is-connected` to avoid introducing extra complexity in the code and keep the program as simple as possible.
To check if a device is connected, you can use `BluetoothDevicePairing.exe discover --discovery-time 2 | findstr /r "Connected.*WH-1000XM5"`
