### ISSUE TITLE
Considering BLE beacon to be scanned?

### ISSUE THREAD

**Issue by Grovkillen** [PolarGoose/BluetoothDevicePairing#2]
https://github.com/andijakl/universal-beacon/

I'd be the first to test it. Would it be something you'd consider turning into a feature of your tool?

**Comment by PolarGoose** [comment]
@Grovkillen,

Sorry, it is beyond of the scope of the BluetoothDevicePairing utility.
It is better to create another console utility for the purpose of working with beacons.
I don't have plans of creating such utility.

**Comment by Grovkillen** [comment]
Totally understand. Keep up the good work on this tool 👍
